### ISSUE TITLE
Research Verification On Signup

### ISSUE THREAD

**Issue by bbmcmann** [hack4impact-calpoly/hospice-of-slo#112]
Shannon would like to be able to validate all new accounts so she can filter new, approved doulas quicker.

Ideally, this would involve her receiving an email that a new user has signed up and she can just hit 'approve', and it would link directly to Firebase.
But maybe this is more easily done via the Firebase console.

Things to consider:
- How easy is it for her to validate?
- How well does it link to Firebase?
- How does it interact with our database?
- Does it require extra work from users (hopefully not)?

After research is complete, will quickly meet with Ben and Ritvik to discuss findings.

**Comment by hopieyimmie** [comment]
[Research .pdf](https://github.com/hack4impact-calpoly/hospice-of-slo/files/10505958/Research.pdf)
