### ISSUE TITLE
Research New Calendar Designs

### ISSUE THREAD

**Issue by bbmcmann** [hack4impact-calpoly/hospice-of-slo#113]
This task will need 2-3 people

Their biggest difficulty has been with the scheduling interface for users.

Shannon wants something similar to the outlook calendar that allows her to visualize the evets easier (especially when side by side) .
She also wants the signup functionality to stay simple for users.

Currently, the site uses the FullCalendar node package for the interface. Please research alternative options to the current design.
Consider:
- Are there other packages that may be easy to use?
- Are there other configurations in FullCalendar that would be easy to change to?
- What else in the site would have to change to accommodate the new calendar?
- How much control do we have over color customization, and other UI elements?

After researching, all researchers will meet together, along with Ritvik and Ben

**Comment by aryaramchander1** [comment]
Some links I found helpful: 
- integrating Google Calendar (convenient for Firebase) into Node.js:
      -  https://www.geeksforgeeks.org/how-to-integrate-google-calendar-in-node-js/
      -  https://flows.nodered.org/node/node-red-contrib-google-oauth-calendar
- Node-calendar: https://www.npmjs.com/package/node-calendar
